// Industrial direct-fired heaters — scraped & cleaned from catalog.pennradiant.com
window.DF_HEATERS = [
  {
    slug:"dg", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"DG Series",
    btu:"241,000 – 394,000 BTU", duct:"Ductable to 50'", img:"hw-dg.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/heat-wagon-dg-series-portable-direct-fired-heater",
    blurb:"Compact dual-rated portable direct-fired heater — efficient forced-air heat for jobsites, shops and agricultural buildings. Changes from vapor propane to natural gas with the turn of a valve.",
    specs:[
      ["Models","DG250 (241,000 BTU) · DG400 (394,000 BTU)"],
      ["Fuel","Vapor propane / natural gas"],
      ["Gas consumption","2.6 GPH LP · 255 CFH NG"],
      ["Air flow","2,766 CFM"],
      ["Electrical","120V · 5 amp"],
      ["Thermostat","On / Off"],
      ["Ductable","Up to 50'"],
    ],
    feats:["Heavy-duty frame with wheels and lifting hook","Changes from vapor propane to natural gas with a turn of a valve","Low amp draw (5.0 / 8.5)","Ductable up to 50'","High-CFM axial fan","Air switch protected by 30-mesh filter","Optional remote thermostat (50' cord) & delay-start relay"],
  },
  {
    slug:"s405", brand:"Sure Flame", brandLogo:"sure-flame.png", model:"S405",
    btu:"400,000 BTU", duct:"Ductable", img:"s405.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/portable-direct-fired-sure-flame-s405-heaters",
    blurb:"Rugged 400,000 BTU dual-fuel portable direct-fired heater built for construction and temporary heat in open, well-ventilated spaces.",
    specs:[
      ["Btu output","400,000 BTU"],
      ["Fuel","Dual fuel — natural gas / vapor propane"],
      ["Air flow","2,000 CFM (¼ hp fan)"],
      ["Electrical","120V · 15 amp"],
      ["Gas connection","1\" NPT"],
      ["Temperature rise","344 °F"],
      ["Dimensions","45.5\"L × 18\"W × 24\"H"],
      ["Weight","107 lb"],
    ],
    feats:["Quick change from LP or natural gas via handle","Air-flow switch & hi-limit switch","Burner heat shield","Flame-safeguard control with electronic ignition","Lifting loop & optional wheel kit","Steel construction","Tested to ANSI standard Z83.7","Indoor / outdoor use"],
  },
  {
    slug:"hw1800b", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"1800B",
    btu:"250,000 – 750,000 BTU", duct:"Ductable to 25'", img:"hw1800b.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/d-heaters-portable-direct-fired-heat-wagon-hw1800b",
    blurb:"High-output forced-air heater, ductable up to 25 feet — ideal for drying, curing and large open-area heating. Hi/Lo firing with included 50' remote thermostat.",
    specs:[
      ["Btu output","250,000 – 750,000 BTU (Hi/Lo)"],
      ["Fuel","Vapor propane / natural gas"],
      ["Air flow","4,200 CFM (1 hp)"],
      ["Electrical","120V · 15 amp"],
      ["Gas connection","3/4\" FNPT"],
      ["Thermostat","Hi / Lo / Off · 50' remote"],
      ["Temperature rise","385 °F"],
      ["Ductable","Up to 25'"],
    ],
    feats:[],
  },
  {
    slug:"hw950h", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"950H Series",
    btu:"400,000 – 950,000 BTU", duct:"Ductable", img:"hw950h.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/ired-heaters-portable-direct-fired-heat-wagon-950h",
    blurb:"950,000 BTU ductable direct-fired heater delivering powerful, consistent forced-air heat for demanding industrial applications.",
    specs:[
      ["Btu output","400,000 – 950,000 BTU (Hi/Lo)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","7,200 CFM"],
      ["Electrical","120V · 15 amp"],
      ["Gas connection","1-1/4\" FNPT"],
      ["Temperature rise","250 °F"],
      ["Ductable","Yes"],
    ],
    feats:[],
  },
  {
    slug:"s1505b", brand:"Sure Flame", brandLogo:"sure-flame.png", model:"S1505B",
    btu:"850,000 – 1,500,000 BTU", duct:"Not ductable", img:"s1505b.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/ed-heaters-portable-direct-fired-sure-flame-s1505b",
    blurb:"Heavy-duty 1.5 million BTU direct-fired heater for very large open spaces where maximum heat output is the priority.",
    specs:[
      ["Btu output","850,000 – 1,500,000 BTU (Hi/Lo)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","7,000 CFM"],
      ["Electrical","120V · 15 amp"],
      ["Gas connection","1-1/4\" FNPT"],
      ["Thermostat","Hi / Lo / Off · 15' remote"],
      ["Temperature rise","490 °F"],
      ["Ductable","No"],
    ],
    feats:[],
  },
  {
    slug:"hw2730c", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"HW2730C Series",
    btu:"500,000 – 2,000,000 BTU", duct:"Ductable", img:"hw2730c.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/-gas-fired-heating-industrial-direct-fired-heaters/portable-direct-fired-heat-wagon-hw2730",
    blurb:"Top-of-the-line 2 million BTU ductable direct-fired heater for the largest structures, drying jobs and temporary-heat projects. Direct-wire with electronic ignition and full safety monitoring.",
    specs:[
      ["Btu output","500,000 (Lo) – 2,000,000 (Hi) BTU"],
      ["Fuel","Natural gas / propane"],
      ["Air flow","12,500 CFM (3 hp)"],
      ["Electrical","240V · 1 phase · 30 amp"],
      ["Gas connection","3/4\""],
      ["Temperature rise","257 °F"],
      ["Dimensions","72\"L × 32\"W × 46\"H"],
      ["Weight","440 lb"],
    ],
    feats:["Direct wire with safe 100% power shut-off","Safe fuel shutdown if combustion air is interrupted","Low housing temperature · indoor / outdoor use","Two-trial electronic ignition with 20-sec pre-purge","Auto Hi/Lo cycling to maintain temperature","Low-voltage & over-fire protection"],
  },
];
