// Heat Wagon VG-series indirect-fired heaters — scraped from catalog.pennradiant.com
window.INDIRECT_HEATERS = [
  {
    slug:"vg400", partsHref:"heat-wagon-vg400-parts.html", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"VG400",
    btu:"320,000 BTU output", img:"vg400.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/ories-gas-fired-heating-indirect-gas-fired-heaters/gas-fired-heating-indirect-gas-fired-heaters-vg400",
    blurb:"Compact Heat Wagon VG400 indirect-fired heater — clean, dry, 100% combustion-separated heat that can be ducted into occupied and enclosed spaces. Ideal for construction, restoration and tenting.",
    specs:[
      ["Btu output","320,000 BTU"],
      ["Heat type","Indirect-fired (clean, dry heat)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","2,100 CFM"],
      ["Gas consumption","4.4 GPH LP · 400 CFH NG"],
      ["Electrical","120V · 20 amp"],
      ["Gas connection","3/4\" FNPT"],
      ["Temperature rise","200 °F"],
      ["Thermostat","On / Off"],
    ],
    feats:["100% indirect — combustion byproducts vented separately for clean, dry heat","Safe to duct into occupied &amp; enclosed spaces","Ductable supply &amp; flue","Propane or natural gas","Heavy-duty frame with wheels","Thermostat controlled"],
  },
  {
    slug:"vg500", partsHref:"heat-wagon-vg500-parts.html", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"VG500",
    btu:"~400,000 BTU output", img:"vg500.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/ories-gas-fired-heating-indirect-gas-fired-heaters/gas-fired-heating-indirect-gas-fired-heaters-vg500",
    blurb:"Heat Wagon VG500 indirect-fired heater delivers clean, dry, ductable heat for mid-size enclosed spaces — construction, restoration, temporary heat and event tenting where air quality matters.",
    specs:[
      ["Btu output","~400,000 BTU"],
      ["Heat type","Indirect-fired (clean, dry heat)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","High-CFM ducted output"],
      ["Thermostat","On / Off"],
    ],
    feats:["100% indirect — clean, dry, breathable heat","Ductable supply &amp; flue for enclosed spaces","Propane or natural gas","Heavy-duty frame with wheels","Thermostat controlled"],
  },
  {
    slug:"vg700c", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"VG700C",
    btu:"~560,000 BTU output", img:"vg700c.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/ories-gas-fired-heating-indirect-gas-fired-heaters/gas-fired-heating-indirect-gas-fired-heaters-vg700",
    blurb:"The high-output Heat Wagon VG700C indirect-fired heater provides powerful clean, dry heat for large enclosed spaces — drying, curing, construction and restoration where occupant comfort and air quality are critical.",
    specs:[
      ["Btu output","~560,000 BTU (700,000 input)"],
      ["Heat type","Indirect-fired (clean, dry heat)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","High-CFM ducted output"],
      ["Thermostat","On / Off"],
    ],
    feats:["100% indirect — combustion separated from the airstream","High-output clean heat for large enclosed areas","Ductable supply &amp; flue","Propane or natural gas","Heavy-duty frame with wheels","Thermostat controlled"],
  },
  {
    slug:"vg1000", partsHref:"heat-wagon-vg1000-parts.html", brand:"Heat Wagon", brandLogo:"heat-wagon.png", model:"VG1000",
    btu:"800,000 BTU output", img:"vg1000.jpg",
    cat:"https://catalog.pennradiant.com/viewitems/ories-gas-fired-heating-indirect-gas-fired-heaters/as-fired-heating-indirect-gas-fired-heaters-vg1000",
    blurb:"The Heat Wagon VG1000 is the top of the indirect-fired line — 800,000 BTU of clean, dry, ductable heat for the largest enclosed structures, drying jobs and temporary-heat projects.",
    specs:[
      ["Btu output","800,000 BTU"],
      ["Heat type","Indirect-fired (clean, dry heat)"],
      ["Fuel","Propane / natural gas"],
      ["Air flow","4,075 CFM"],
      ["Gas consumption","11 GPH LP · 1,000 CFH NG"],
      ["Electrical","240V · 1 phase · 30 amp"],
      ["Gas connection","1-1/4\" FNPT"],
      ["Temperature rise","200 °F"],
      ["Thermostat","On / Off"],
    ],
    feats:["800,000 BTU of 100% indirect clean, dry heat","Safe to duct into the largest occupied / enclosed spaces","Ductable supply &amp; flue","Propane or natural gas","Heavy-duty frame with wheels","Thermostat controlled"],
  },
];
